// List of universities in Bangladesh (public + private + national + specialized)
export const BD_UNIVERSITIES: { name: string; type: 'Public' | 'Private' | 'International' | 'Specialized' }[] = [
  // Public General
  { name: 'University of Dhaka', type: 'Public' },
  { name: 'University of Rajshahi', type: 'Public' },
  { name: 'University of Chittagong', type: 'Public' },
  { name: 'Jahangirnagar University', type: 'Public' },
  { name: 'Islamic University, Bangladesh', type: 'Public' },
  { name: 'Khulna University', type: 'Public' },
  { name: 'National University, Bangladesh', type: 'Public' },
  { name: 'Bangladesh Open University', type: 'Public' },
  { name: 'Shahjalal University of Science and Technology (SUST)', type: 'Public' },
  { name: 'Hajee Mohammad Danesh Science and Technology University', type: 'Public' },
  { name: 'Mawlana Bhashani Science and Technology University', type: 'Public' },
  { name: 'Patuakhali Science and Technology University', type: 'Public' },
  { name: 'Noakhali Science and Technology University', type: 'Public' },
  { name: 'Jagannath University', type: 'Public' },
  { name: 'Comilla University', type: 'Public' },
  { name: 'Jatiya Kabi Kazi Nazrul Islam University', type: 'Public' },
  { name: 'Begum Rokeya University, Rangpur', type: 'Public' },
  { name: 'Bangabandhu Sheikh Mujibur Rahman Science and Technology University', type: 'Public' },
  { name: 'Pabna University of Science and Technology', type: 'Public' },
  { name: 'Bangladesh University of Professionals (BUP)', type: 'Public' },
  { name: 'Rangamati Science and Technology University', type: 'Public' },
  { name: 'Rabindra University, Bangladesh', type: 'Public' },
  { name: 'Bangabandhu Sheikh Mujibur Rahman Digital University', type: 'Public' },
  { name: 'Sheikh Hasina University', type: 'Public' },
  { name: 'Khulna Agricultural University', type: 'Public' },
  { name: 'Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University', type: 'Public' },
  { name: 'Chandpur Science and Technology University', type: 'Public' },
  { name: 'Habiganj Agricultural University', type: 'Public' },
  { name: 'Kishoreganj University', type: 'Public' },
  { name: 'Sunamganj Science and Technology University', type: 'Public' },
  { name: 'Pirojpur Science and Technology University', type: 'Public' },
  { name: 'Meherpur University', type: 'Public' },
  { name: 'Naogaon University', type: 'Public' },
  { name: 'Lakshmipur Science and Technology University', type: 'Public' },
  { name: 'Thakurgaon University', type: 'Public' },

  // Public Engineering / Specialized
  { name: 'Bangladesh University of Engineering and Technology (BUET)', type: 'Public' },
  { name: 'Rajshahi University of Engineering & Technology (RUET)', type: 'Public' },
  { name: 'Khulna University of Engineering & Technology (KUET)', type: 'Public' },
  { name: 'Chittagong University of Engineering & Technology (CUET)', type: 'Public' },
  { name: 'Dhaka University of Engineering & Technology (DUET)', type: 'Public' },
  { name: 'Bangladesh Textile University', type: 'Public' },
  { name: 'Bangladesh University of Textiles', type: 'Public' },
  { name: 'Military Institute of Science and Technology (MIST)', type: 'Public' },

  // Public Medical
  { name: 'Bangabandhu Sheikh Mujib Medical University (BSMMU)', type: 'Public' },
  { name: 'Chittagong Medical University', type: 'Public' },
  { name: 'Rajshahi Medical University', type: 'Public' },
  { name: 'Sylhet Medical University', type: 'Public' },
  { name: 'Dhaka Medical College', type: 'Public' },
  { name: 'Sir Salimullah Medical College', type: 'Public' },

  // Public Agriculture
  { name: 'Bangladesh Agricultural University', type: 'Public' },
  { name: 'Sher-e-Bangla Agricultural University', type: 'Public' },
  { name: 'Sylhet Agricultural University', type: 'Public' },
  { name: 'Chittagong Veterinary and Animal Sciences University', type: 'Public' },
  { name: 'Bangabandhu Sheikh Mujibur Rahman Agricultural University', type: 'Public' },

  // Public Arts / Islamic
  { name: 'Islamic Arabic University', type: 'Public' },
  { name: 'Bangladesh University of Textiles', type: 'Public' },
  { name: 'University of Liberal Arts Bangladesh (ULAB)', type: 'Private' },

  // Top Private
  { name: 'BRAC University', type: 'Private' },
  { name: 'North South University (NSU)', type: 'Private' },
  { name: 'Independent University, Bangladesh (IUB)', type: 'Private' },
  { name: 'American International University-Bangladesh (AIUB)', type: 'Private' },
  { name: 'East West University', type: 'Private' },
  { name: 'Ahsanullah University of Science and Technology (AUST)', type: 'Private' },
  { name: 'United International University (UIU)', type: 'Private' },
  { name: 'Daffodil International University', type: 'Private' },
  { name: 'University of Asia Pacific (UAP)', type: 'Private' },
  { name: 'Southeast University', type: 'Private' },
  { name: 'Stamford University Bangladesh', type: 'Private' },
  { name: 'Eastern University', type: 'Private' },
  { name: 'Northern University Bangladesh', type: 'Private' },
  { name: 'Green University of Bangladesh', type: 'Private' },
  { name: 'World University of Bangladesh', type: 'Private' },
  { name: 'Bangladesh University of Business and Technology (BUBT)', type: 'Private' },
  { name: 'Manarat International University', type: 'Private' },
  { name: 'Presidency University', type: 'Private' },
  { name: 'State University of Bangladesh', type: 'Private' },
  { name: 'Asian University of Bangladesh', type: 'Private' },
  { name: 'Bangladesh University', type: 'Private' },
  { name: 'City University', type: 'Private' },
  { name: 'Prime University', type: 'Private' },
  { name: 'European University of Bangladesh', type: 'Private' },
  { name: 'Atish Dipankar University of Science and Technology', type: 'Private' },
  { name: 'Britannia University', type: 'Private' },
  { name: 'CCN University of Science and Technology', type: 'Private' },
  { name: 'Central Women’s University', type: 'Private' },
  { name: 'Cox’s Bazar International University', type: 'Private' },
  { name: 'Dhaka International University', type: 'Private' },
  { name: 'Exim Bank Agricultural University Bangladesh', type: 'Private' },
  { name: 'Fareast International University', type: 'Private' },
  { name: 'First Capital University of Bangladesh', type: 'Private' },
  { name: 'German University Bangladesh', type: 'Private' },
  { name: 'Gono Bishwabidyalay', type: 'Private' },
  { name: 'Hamdard University Bangladesh', type: 'Private' },
  { name: 'IBAIS University', type: 'Private' },
  { name: 'International Islamic University Chittagong (IIUC)', type: 'Private' },
  { name: 'International University of Business Agriculture and Technology (IUBAT)', type: 'Private' },
  { name: 'Ishakha International University, Bangladesh', type: 'Private' },
  { name: 'Khwaja Yunus Ali University', type: 'Private' },
  { name: 'Leading University', type: 'Private' },
  { name: 'Metropolitan University, Sylhet', type: 'Private' },
  { name: 'North Bengal International University', type: 'Private' },
  { name: 'North East University Bangladesh', type: 'Private' },
  { name: 'North Western University', type: 'Private' },
  { name: 'Notre Dame University Bangladesh', type: 'Private' },
  { name: 'People’s University of Bangladesh', type: 'Private' },
  { name: 'Port City International University', type: 'Private' },
  { name: 'Premier University, Chittagong', type: 'Private' },
  { name: 'Pundra University of Science and Technology', type: 'Private' },
  { name: 'Queens University', type: 'Private' },
  { name: 'Ranada Prasad Shaha University', type: 'Private' },
  { name: 'Royal University of Dhaka', type: 'Private' },
  { name: 'Shanto-Mariam University of Creative Technology', type: 'Private' },
  { name: 'Sonargaon University', type: 'Private' },
  { name: 'Southern University Bangladesh', type: 'Private' },
  { name: 'Sylhet International University', type: 'Private' },
  { name: 'The International University of Scholars', type: 'Private' },
  { name: 'The Millennium University', type: 'Private' },
  { name: 'The People’s University of Bangladesh', type: 'Private' },
  { name: 'The University of Comilla', type: 'Private' },
  { name: 'University of Creative Technology, Chittagong', type: 'Private' },
  { name: 'University of Development Alternative (UODA)', type: 'Private' },
  { name: 'University of Global Village', type: 'Private' },
  { name: 'University of Information Technology and Sciences (UITS)', type: 'Private' },
  { name: 'University of Science & Technology Chittagong (USTC)', type: 'Private' },
  { name: 'University of South Asia', type: 'Private' },
  { name: 'Uttara University', type: 'Private' },
  { name: 'Varendra University', type: 'Private' },
  { name: 'Victoria University of Bangladesh', type: 'Private' },
  { name: 'Z. H. Sikder University of Science and Technology', type: 'Private' },

  // International
  { name: 'Asian University for Women', type: 'International' },
  { name: 'Canadian University of Bangladesh', type: 'International' },
];

export const UNIVERSITY_OPTIONS = BD_UNIVERSITIES.map(u => ({
  value: u.name,
  label: u.name,
  group: u.type,
}));
