-- Create payment transactions table for SSLCommerz
CREATE TABLE public.payment_transactions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  transaction_id TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL,
  amount NUMERIC NOT NULL,
  currency TEXT NOT NULL DEFAULT 'BDT',
  status TEXT NOT NULL DEFAULT 'pending',
  plan_id UUID REFERENCES public.subscription_plans(id),
  listing_type TEXT,
  validation_id TEXT,
  gateway_response JSONB,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

-- Users can view own transactions
CREATE POLICY "Users can view own transactions"
ON public.payment_transactions FOR SELECT
USING (auth.uid() = user_id);

-- Create index
CREATE INDEX idx_payment_transactions_user ON public.payment_transactions(user_id);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions(status);

-- ==================== DEMO DATA ====================

-- Insert 64 Districts of Bangladesh
INSERT INTO public.districts (id, name_en, name_bn, division_en, division_bn) VALUES
  (gen_random_uuid(), 'Dhaka', 'ঢাকা', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Gazipur', 'গাজীপুর', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Narayanganj', 'নারায়ণগঞ্জ', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Tangail', 'টাঙ্গাইল', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Kishoreganj', 'কিশোরগঞ্জ', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Manikganj', 'মানিকগঞ্জ', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Munshiganj', 'মুন্সিগঞ্জ', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Narsingdi', 'নরসিংদী', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Faridpur', 'ফরিদপুর', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Gopalganj', 'গোপালগঞ্জ', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Madaripur', 'মাদারীপুর', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Rajbari', 'রাজবাড়ী', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Shariatpur', 'শরীয়তপুর', 'Dhaka', 'ঢাকা'),
  (gen_random_uuid(), 'Chattogram', 'চট্টগ্রাম', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Comilla', 'কুমিল্লা', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Brahmanbaria', 'ব্রাহ্মণবাড়িয়া', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Chandpur', 'চাঁদপুর', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Feni', 'ফেনী', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Lakshmipur', 'লক্ষ্মীপুর', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Noakhali', 'নোয়াখালী', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Coxs Bazar', 'কক্সবাজার', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Khagrachhari', 'খাগড়াছড়ি', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Rangamati', 'রাঙ্গামাটি', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Bandarban', 'বান্দরবান', 'Chattogram', 'চট্টগ্রাম'),
  (gen_random_uuid(), 'Rajshahi', 'রাজশাহী', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Bogra', 'বগুড়া', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Joypurhat', 'জয়পুরহাট', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Naogaon', 'নওগাঁ', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Natore', 'নাটোর', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Nawabganj', 'নবাবগঞ্জ', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Pabna', 'পাবনা', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Sirajganj', 'সিরাজগঞ্জ', 'Rajshahi', 'রাজশাহী'),
  (gen_random_uuid(), 'Khulna', 'খুলনা', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Bagerhat', 'বাগেরহাট', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Chuadanga', 'চুয়াডাঙ্গা', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Jessore', 'যশোর', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Jhenaidah', 'ঝিনাইদহ', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Kushtia', 'কুষ্টিয়া', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Magura', 'মাগুরা', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Meherpur', 'মেহেরপুর', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Narail', 'নড়াইল', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Satkhira', 'সাতক্ষীরা', 'Khulna', 'খুলনা'),
  (gen_random_uuid(), 'Sylhet', 'সিলেট', 'Sylhet', 'সিলেট'),
  (gen_random_uuid(), 'Habiganj', 'হবিগঞ্জ', 'Sylhet', 'সিলেট'),
  (gen_random_uuid(), 'Moulvibazar', 'মৌলভীবাজার', 'Sylhet', 'সিলেট'),
  (gen_random_uuid(), 'Sunamganj', 'সুনামগঞ্জ', 'Sylhet', 'সিলেট'),
  (gen_random_uuid(), 'Rangpur', 'রংপুর', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Dinajpur', 'দিনাজপুর', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Gaibandha', 'গাইবান্ধা', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Kurigram', 'কুড়িগ্রাম', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Lalmonirhat', 'লালমনিরহাট', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Nilphamari', 'নীলফামারী', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Panchagarh', 'পঞ্চগড়', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Thakurgaon', 'ঠাকুরগাঁও', 'Rangpur', 'রংপুর'),
  (gen_random_uuid(), 'Barisal', 'বরিশাল', 'Barisal', 'বরিশাল'),
  (gen_random_uuid(), 'Barguna', 'বরগুনা', 'Barisal', 'বরিশাল'),
  (gen_random_uuid(), 'Bhola', 'ভোলা', 'Barisal', 'বরিশাল'),
  (gen_random_uuid(), 'Jhalokati', 'ঝালকাঠি', 'Barisal', 'বরিশাল'),
  (gen_random_uuid(), 'Patuakhali', 'পটুয়াখালী', 'Barisal', 'বরিশাল'),
  (gen_random_uuid(), 'Pirojpur', 'পিরোজপুর', 'Barisal', 'বরিশাল'),
  (gen_random_uuid(), 'Mymensingh', 'ময়মনসিংহ', 'Mymensingh', 'ময়মনসিংহ'),
  (gen_random_uuid(), 'Jamalpur', 'জামালপুর', 'Mymensingh', 'ময়মনসিংহ'),
  (gen_random_uuid(), 'Netrokona', 'নেত্রকোনা', 'Mymensingh', 'ময়মনসিংহ'),
  (gen_random_uuid(), 'Sherpur', 'শেরপুর', 'Mymensingh', 'ময়মনসিংহ')
ON CONFLICT DO NOTHING;

-- Insert 50+ Subjects
INSERT INTO public.subjects (id, name_en, name_bn, category_en, category_bn) VALUES
  (gen_random_uuid(), 'Bangla', 'বাংলা', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'English', 'ইংরেজি', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'Mathematics', 'গণিত', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Physics', 'পদার্থবিজ্ঞান', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Chemistry', 'রসায়ন', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Biology', 'জীববিজ্ঞান', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Higher Math', 'উচ্চতর গণিত', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'ICT', 'তথ্য ও যোগাযোগ প্রযুক্তি', 'Technology', 'প্রযুক্তি'),
  (gen_random_uuid(), 'General Science', 'সাধারণ বিজ্ঞান', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Social Science', 'সামাজিক বিজ্ঞান', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'History', 'ইতিহাস', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Geography', 'ভূগোল', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Economics', 'অর্থনীতি', 'Business', 'বাণিজ্য'),
  (gen_random_uuid(), 'Accounting', 'হিসাববিজ্ঞান', 'Business', 'বাণিজ্য'),
  (gen_random_uuid(), 'Business Studies', 'ব্যবসায় শিক্ষা', 'Business', 'বাণিজ্য'),
  (gen_random_uuid(), 'Finance', 'ফিন্যান্স', 'Business', 'বাণিজ্য'),
  (gen_random_uuid(), 'Statistics', 'পরিসংখ্যান', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Islamic Studies', 'ইসলাম শিক্ষা', 'Religious', 'ধর্মীয়'),
  (gen_random_uuid(), 'Arabic', 'আরবি', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'Quran Recitation', 'কোরআন তেলাওয়াত', 'Religious', 'ধর্মীয়'),
  (gen_random_uuid(), 'Hindu Studies', 'হিন্দু ধর্ম শিক্ষা', 'Religious', 'ধর্মীয়'),
  (gen_random_uuid(), 'Agriculture', 'কৃষি শিক্ষা', 'Vocational', 'বৃত্তিমূলক'),
  (gen_random_uuid(), 'Home Science', 'গার্হস্থ্য বিজ্ঞান', 'Vocational', 'বৃত্তিমূলক'),
  (gen_random_uuid(), 'Computer Science', 'কম্পিউটার বিজ্ঞান', 'Technology', 'প্রযুক্তি'),
  (gen_random_uuid(), 'Programming', 'প্রোগ্রামিং', 'Technology', 'প্রযুক্তি'),
  (gen_random_uuid(), 'Web Development', 'ওয়েব ডেভেলপমেন্ট', 'Technology', 'প্রযুক্তি'),
  (gen_random_uuid(), 'Graphic Design', 'গ্রাফিক ডিজাইন', 'Arts', 'চারুকলা'),
  (gen_random_uuid(), 'Drawing', 'অঙ্কন', 'Arts', 'চারুকলা'),
  (gen_random_uuid(), 'Music', 'সঙ্গীত', 'Arts', 'চারুকলা'),
  (gen_random_uuid(), 'Guitar', 'গিটার', 'Arts', 'চারুকলা'),
  (gen_random_uuid(), 'Piano', 'পিয়ানো', 'Arts', 'চারুকলা'),
  (gen_random_uuid(), 'Spoken English', 'স্পোকেন ইংলিশ', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'IELTS Preparation', 'আইইএলটিএস প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'SAT Preparation', 'এসএটি প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'GRE Preparation', 'জিআরই প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'Medical Admission', 'মেডিকেল ভর্তি প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'Engineering Admission', 'ইঞ্জিনিয়ারিং ভর্তি প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'University Admission', 'বিশ্ববিদ্যালয় ভর্তি প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'BCS Preparation', 'বিসিএস প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'Bank Job Preparation', 'ব্যাংক জব প্রস্তুতি', 'Test Prep', 'পরীক্ষার প্রস্তুতি'),
  (gen_random_uuid(), 'Civics', 'পৌরনীতি', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Logic', 'যুক্তিবিদ্যা', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Psychology', 'মনোবিজ্ঞান', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Sociology', 'সমাজবিজ্ঞান', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Political Science', 'রাষ্ট্রবিজ্ঞান', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Philosophy', 'দর্শন', 'Humanities', 'মানবিক'),
  (gen_random_uuid(), 'Environmental Science', 'পরিবেশ বিজ্ঞান', 'Science', 'বিজ্ঞান'),
  (gen_random_uuid(), 'Physical Education', 'শারীরিক শিক্ষা', 'Sports', 'খেলাধুলা'),
  (gen_random_uuid(), 'French', 'ফরাসি', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'German', 'জার্মান', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'Japanese', 'জাপানি', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'Chinese', 'চীনা', 'Languages', 'ভাষা'),
  (gen_random_uuid(), 'Korean', 'কোরিয়ান', 'Languages', 'ভাষা')
ON CONFLICT DO NOTHING;