-- Create a demo_profiles table for display purposes (not linked to auth)
CREATE TABLE IF NOT EXISTS public.demo_profiles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  full_name TEXT NOT NULL,
  full_name_bn TEXT,
  email TEXT,
  phone TEXT,
  avatar_url TEXT,
  district_id UUID REFERENCES public.districts(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS and allow public read
ALTER TABLE public.demo_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Demo profiles are viewable" ON public.demo_profiles FOR SELECT USING (true);

-- Insert 60 demo tutor profiles with display data
INSERT INTO public.demo_profiles (id, full_name, full_name_bn, email, phone, district_id) VALUES
  (gen_random_uuid(), 'Md. Tanvir Hasan', 'মো. তানভীর হাসান', 'tanvir@demo.com', '01712345601', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Anika Rahman', 'অনিকা রহমান', 'anika@demo.com', '01712345602', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Sabbir Ahmed', 'সাব্বির আহমেদ', 'sabbir@demo.com', '01712345603', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Nusrat Jahan', 'নুসরাত জাহান', 'nusrat@demo.com', '01712345604', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Rafiqul Islam', 'রফিকুল ইসলাম', 'rafiq@demo.com', '01712345605', (SELECT id FROM districts WHERE name_en = 'Rajshahi' LIMIT 1)),
  (gen_random_uuid(), 'Tasnim Ferdous', 'তাসনিম ফেরদৌস', 'tasnim@demo.com', '01712345606', (SELECT id FROM districts WHERE name_en = 'Khulna' LIMIT 1)),
  (gen_random_uuid(), 'Imran Hossain', 'ইমরান হোসেন', 'imran@demo.com', '01712345607', (SELECT id FROM districts WHERE name_en = 'Sylhet' LIMIT 1)),
  (gen_random_uuid(), 'Farzana Yasmin', 'ফারজানা ইয়াসমিন', 'farzana@demo.com', '01712345608', (SELECT id FROM districts WHERE name_en = 'Rangpur' LIMIT 1)),
  (gen_random_uuid(), 'Shakil Ahmed', 'শাকিল আহমেদ', 'shakil@demo.com', '01712345609', (SELECT id FROM districts WHERE name_en = 'Barisal' LIMIT 1)),
  (gen_random_uuid(), 'Maliha Tabassum', 'মালিহা তাবাসসুম', 'maliha@demo.com', '01712345610', (SELECT id FROM districts WHERE name_en = 'Mymensingh' LIMIT 1)),
  (gen_random_uuid(), 'Rakibul Hasan', 'রাকিবুল হাসান', 'rakib@demo.com', '01712345611', (SELECT id FROM districts WHERE name_en = 'Gazipur' LIMIT 1)),
  (gen_random_uuid(), 'Sumaiya Akter', 'সুমাইয়া আক্তার', 'sumaiya@demo.com', '01712345612', (SELECT id FROM districts WHERE name_en = 'Narayanganj' LIMIT 1)),
  (gen_random_uuid(), 'Masud Rana', 'মাসুদ রানা', 'masud@demo.com', '01712345613', (SELECT id FROM districts WHERE name_en = 'Comilla' LIMIT 1)),
  (gen_random_uuid(), 'Tahira Khanam', 'তাহিরা খানম', 'tahira@demo.com', '01712345614', (SELECT id FROM districts WHERE name_en = 'Bogra' LIMIT 1)),
  (gen_random_uuid(), 'Arif Mahmud', 'আরিফ মাহমুদ', 'arif@demo.com', '01712345615', (SELECT id FROM districts WHERE name_en = 'Jessore' LIMIT 1)),
  (gen_random_uuid(), 'Rabeya Sultana', 'রাবেয়া সুলতানা', 'rabeya@demo.com', '01712345616', (SELECT id FROM districts WHERE name_en = 'Dinajpur' LIMIT 1)),
  (gen_random_uuid(), 'Sohel Rana', 'সোহেল রানা', 'sohel@demo.com', '01712345617', (SELECT id FROM districts WHERE name_en = 'Tangail' LIMIT 1)),
  (gen_random_uuid(), 'Lamia Akter', 'লামিয়া আক্তার', 'lamia@demo.com', '01712345618', (SELECT id FROM districts WHERE name_en = 'Faridpur' LIMIT 1)),
  (gen_random_uuid(), 'Farhan Ahmed', 'ফারহান আহমেদ', 'farhan@demo.com', '01712345619', (SELECT id FROM districts WHERE name_en = 'Brahmanbaria' LIMIT 1)),
  (gen_random_uuid(), 'Sadia Islam', 'সাদিয়া ইসলাম', 'sadia@demo.com', '01712345620', (SELECT id FROM districts WHERE name_en = 'Pabna' LIMIT 1)),
  (gen_random_uuid(), 'Jubayer Hossain', 'জুবায়ের হোসেন', 'jubayer@demo.com', '01712345621', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Nafisa Rahman', 'নাফিসা রহমান', 'nafisa@demo.com', '01712345622', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Tahmid Hassan', 'তাহমিদ হাসান', 'tahmid@demo.com', '01712345623', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Jannatul Ferdous', 'জান্নাতুল ফেরদৌস', 'jannatul@demo.com', '01712345624', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Rezaul Karim', 'রেজাউল করিম', 'rezaul@demo.com', '01712345625', (SELECT id FROM districts WHERE name_en = 'Rajshahi' LIMIT 1)),
  (gen_random_uuid(), 'Sharmin Sultana', 'শারমিন সুলতানা', 'sharmin@demo.com', '01712345626', (SELECT id FROM districts WHERE name_en = 'Khulna' LIMIT 1)),
  (gen_random_uuid(), 'Saiful Islam', 'সাইফুল ইসলাম', 'saiful@demo.com', '01712345627', (SELECT id FROM districts WHERE name_en = 'Sylhet' LIMIT 1)),
  (gen_random_uuid(), 'Rumana Akter', 'রুমানা আক্তার', 'rumana@demo.com', '01712345628', (SELECT id FROM districts WHERE name_en = 'Rangpur' LIMIT 1)),
  (gen_random_uuid(), 'Mehedi Hasan', 'মেহেদী হাসান', 'mehedi@demo.com', '01712345629', (SELECT id FROM districts WHERE name_en = 'Barisal' LIMIT 1)),
  (gen_random_uuid(), 'Fahmida Khanom', 'ফাহমিদা খানম', 'fahmida@demo.com', '01712345630', (SELECT id FROM districts WHERE name_en = 'Mymensingh' LIMIT 1)),
  (gen_random_uuid(), 'Ashik Mahmud', 'আশিক মাহমুদ', 'ashik@demo.com', '01712345631', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Fatema Tuz Zohra', 'ফাতেমা তুজ জোহরা', 'fatema@demo.com', '01712345632', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Nazmul Haque', 'নাজমুল হক', 'nazmul@demo.com', '01712345633', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Ayesha Siddiqua', 'আয়েশা সিদ্দিকা', 'ayesha@demo.com', '01712345634', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Hasan Mahmud', 'হাসান মাহমুদ', 'hasan@demo.com', '01712345635', (SELECT id FROM districts WHERE name_en = 'Rajshahi' LIMIT 1)),
  (gen_random_uuid(), 'Tania Sultana', 'তানিয়া সুলতানা', 'tania@demo.com', '01712345636', (SELECT id FROM districts WHERE name_en = 'Khulna' LIMIT 1)),
  (gen_random_uuid(), 'Zahid Hasan', 'জাহিদ হাসান', 'zahid@demo.com', '01712345637', (SELECT id FROM districts WHERE name_en = 'Sylhet' LIMIT 1)),
  (gen_random_uuid(), 'Mariam Akter', 'মরিয়ম আক্তার', 'mariam@demo.com', '01712345638', (SELECT id FROM districts WHERE name_en = 'Rangpur' LIMIT 1)),
  (gen_random_uuid(), 'Rony Ahmed', 'রনি আহমেদ', 'rony@demo.com', '01712345639', (SELECT id FROM districts WHERE name_en = 'Barisal' LIMIT 1)),
  (gen_random_uuid(), 'Jesmin Ara', 'জেসমিন আরা', 'jesmin@demo.com', '01712345640', (SELECT id FROM districts WHERE name_en = 'Mymensingh' LIMIT 1)),
  (gen_random_uuid(), 'Kawsar Ahmed', 'কাওসার আহমেদ', 'kawsar@demo.com', '01712345641', (SELECT id FROM districts WHERE name_en = 'Gazipur' LIMIT 1)),
  (gen_random_uuid(), 'Shamima Nasrin', 'শামিমা নাসরিন', 'shamima@demo.com', '01712345642', (SELECT id FROM districts WHERE name_en = 'Narayanganj' LIMIT 1)),
  (gen_random_uuid(), 'Billal Hossain', 'বিল্লাল হোসেন', 'billal@demo.com', '01712345643', (SELECT id FROM districts WHERE name_en = 'Comilla' LIMIT 1)),
  (gen_random_uuid(), 'Nasima Begum', 'নাসিমা বেগম', 'nasima@demo.com', '01712345644', (SELECT id FROM districts WHERE name_en = 'Bogra' LIMIT 1)),
  (gen_random_uuid(), 'Jahangir Alam', 'জাহাঙ্গীর আলম', 'jahangir@demo.com', '01712345645', (SELECT id FROM districts WHERE name_en = 'Jessore' LIMIT 1)),
  (gen_random_uuid(), 'Shanta Islam', 'শান্তা ইসলাম', 'shanta@demo.com', '01712345646', (SELECT id FROM districts WHERE name_en = 'Dinajpur' LIMIT 1)),
  (gen_random_uuid(), 'Ripon Das', 'রিপন দাস', 'ripon@demo.com', '01712345647', (SELECT id FROM districts WHERE name_en = 'Tangail' LIMIT 1)),
  (gen_random_uuid(), 'Moushumi Rahman', 'মৌসুমী রহমান', 'moushumi@demo.com', '01712345648', (SELECT id FROM districts WHERE name_en = 'Faridpur' LIMIT 1)),
  (gen_random_uuid(), 'Shahadat Hossain', 'শাহাদাত হোসেন', 'shahadat@demo.com', '01712345649', (SELECT id FROM districts WHERE name_en = 'Brahmanbaria' LIMIT 1)),
  (gen_random_uuid(), 'Ratna Begum', 'রত্না বেগম', 'ratna@demo.com', '01712345650', (SELECT id FROM districts WHERE name_en = 'Pabna' LIMIT 1)),
  (gen_random_uuid(), 'Monir Hossain', 'মনির হোসেন', 'monir@demo.com', '01712345651', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Rubina Akter', 'রুবিনা আক্তার', 'rubina@demo.com', '01712345652', (SELECT id FROM districts WHERE name_en = 'Dhaka' LIMIT 1)),
  (gen_random_uuid(), 'Shohag Mia', 'সোহাগ মিয়া', 'shohag@demo.com', '01712345653', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Lima Akter', 'লিমা আক্তার', 'lima@demo.com', '01712345654', (SELECT id FROM districts WHERE name_en = 'Chattogram' LIMIT 1)),
  (gen_random_uuid(), 'Jafor Iqbal', 'জাফর ইকবাল', 'jafor@demo.com', '01712345655', (SELECT id FROM districts WHERE name_en = 'Rajshahi' LIMIT 1)),
  (gen_random_uuid(), 'Roksana Parvin', 'রোকসানা পারভিন', 'roksana@demo.com', '01712345656', (SELECT id FROM districts WHERE name_en = 'Khulna' LIMIT 1)),
  (gen_random_uuid(), 'Alamgir Kabir', 'আলমগীর কবির', 'alamgir@demo.com', '01712345657', (SELECT id FROM districts WHERE name_en = 'Sylhet' LIMIT 1)),
  (gen_random_uuid(), 'Monika Rani', 'মনিকা রানী', 'monika@demo.com', '01712345658', (SELECT id FROM districts WHERE name_en = 'Rangpur' LIMIT 1)),
  (gen_random_uuid(), 'Delwar Hossain', 'দেলোয়ার হোসেন', 'delwar@demo.com', '01712345659', (SELECT id FROM districts WHERE name_en = 'Barisal' LIMIT 1)),
  (gen_random_uuid(), 'Hafsa Khatun', 'হাফসা খাতুন', 'hafsa@demo.com', '01712345660', (SELECT id FROM districts WHERE name_en = 'Mymensingh' LIMIT 1));